// Mocks generated by Mockito 5.0.14 from annotations
// in indian_cricket_league/test/login_page_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:indian_cricket_league/repository/sign_in_repository.dart'
    as _i4;
import 'package:indian_cricket_league/services/sign_in_services.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeSignInServices_0 extends _i1.Fake implements _i2.SignInServices {}

class _FakeFirebaseAuth_1 extends _i1.Fake implements _i3.FirebaseAuth {}

/// A class which mocks [SignInRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInRepository extends _i1.Mock implements _i4.SignInRepository {
  MockSignInRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SignInServices get services =>
      (super.noSuchMethod(Invocation.getter(#services),
          returnValue: _FakeSignInServices_0()) as _i2.SignInServices);
  @override
  set services(_i2.SignInServices? _services) =>
      super.noSuchMethod(Invocation.setter(#services, _services),
          returnValueForMissingStub: null);
  @override
  _i5.Future<bool> isUserLoggedIn() =>
      (super.noSuchMethod(Invocation.method(#isUserLoggedIn, []),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<dynamic> createUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(Invocation.method(#createUser, [userData]),
          returnValue: Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> loginUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(Invocation.method(#loginUser, [userData]),
          returnValue: Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> signOut() =>
      (super.noSuchMethod(Invocation.method(#signOut, []),
          returnValue: Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SignInServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInServices extends _i1.Mock implements _i2.SignInServices {
  MockSignInServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FirebaseAuth get auth => (super.noSuchMethod(Invocation.getter(#auth),
      returnValue: _FakeFirebaseAuth_1()) as _i3.FirebaseAuth);
  @override
  set auth(_i3.FirebaseAuth? _auth) =>
      super.noSuchMethod(Invocation.setter(#auth, _auth),
          returnValueForMissingStub: null);
  @override
  _i5.Future<bool> isUserLoggedIn() =>
      (super.noSuchMethod(Invocation.method(#isUserLoggedIn, []),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<dynamic> createUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(Invocation.method(#createUser, [userData]),
          returnValue: Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> loginUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(Invocation.method(#loginUser, [userData]),
          returnValue: Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> signOut() =>
      (super.noSuchMethod(Invocation.method(#signOut, []),
          returnValue: Future<dynamic>.value()) as _i5.Future<dynamic>);
  @override
  String toString() => super.toString();
}
